export interface Product {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviews: number;
  image: string;
  badge?: string;
  category: string;
  description: string;
}

export const allProducts: Product[] = [
  // Electronics
  {
    id: '1',
    name: 'Premium Wireless Headphones with Active Noise Cancelling',
    price: 199.99,
    originalPrice: 299.99,
    rating: 4.8,
    reviews: 2847,
    image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg',
    badge: 'Best Seller',
    category: 'Electronics',
    description: 'Experience premium audio quality with our flagship wireless headphones featuring advanced noise cancellation technology.',
  },
  {
    id: '2',
    name: 'Smart Watch with Health Monitoring & GPS',
    price: 299.99,
    originalPrice: 399.99,
    rating: 4.6,
    reviews: 1532,
    image: 'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg',
    badge: 'New',
    category: 'Electronics',
    description: 'Stay connected and healthy with our advanced smartwatch featuring comprehensive health monitoring and GPS tracking.',
  },
  {
    id: '4',
    name: 'Professional 4K Wireless Camera System',
    price: 899.99,
    originalPrice: 1199.99,
    rating: 4.7,
    reviews: 687,
    image: 'https://images.pexels.com/photos/51383/photo-camera-subject-photographer-51383.jpeg',
    badge: 'Sale',
    category: 'Electronics',
    description: 'Capture life in stunning 4K resolution with our professional-grade wireless camera system perfect for content creators.',
  },
  {
    id: '6',
    name: 'Smart Home Security Camera with AI Detection',
    price: 179.99,
    rating: 4.5,
    reviews: 1823,
    image: 'https://images.pexels.com/photos/430208/pexels-photo-430208.jpeg',
    category: 'Electronics',
    description: 'Protect your home with intelligent AI-powered security camera featuring facial recognition and smart alerts.',
  },
  {
    id: '8',
    name: 'Wireless Gaming Mouse with RGB Lighting',
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.7,
    reviews: 2156,
    image: 'https://images.pexels.com/photos/2115256/pexels-photo-2115256.jpeg',
    category: 'Electronics',
    description: 'Dominate your games with our precision wireless gaming mouse featuring customizable RGB lighting and ultra-fast response.',
  },
  {
    id: 'e1',
    name: 'Ultra-Wide 4K Gaming Monitor',
    price: 649.99,
    originalPrice: 799.99,
    rating: 4.8,
    reviews: 1245,
    image: 'https://images.pexels.com/photos/777001/pexels-photo-777001.jpeg',
    badge: 'Gaming',
    category: 'Electronics',
    description: 'Immerse yourself in gaming with this stunning ultra-wide 4K monitor featuring HDR and 144Hz refresh rate.',
  },
  {
    id: 'e2',
    name: 'Bluetooth Wireless Earbuds Pro',
    price: 149.99,
    originalPrice: 199.99,
    rating: 4.6,
    reviews: 3421,
    image: 'https://images.pexels.com/photos/8534088/pexels-photo-8534088.jpeg',
    category: 'Electronics',
    description: 'Premium wireless earbuds with crystal clear sound, active noise cancellation, and all-day battery life.',
  },
  {
    id: 'e3',
    name: 'Smart Home Hub with Voice Control',
    price: 129.99,
    rating: 4.4,
    reviews: 892,
    image: 'https://images.pexels.com/photos/4219654/pexels-photo-4219654.jpeg',
    badge: 'Smart Home',
    category: 'Electronics',
    description: 'Control your entire smart home with voice commands and automated routines through this intelligent hub.',
  },

  // Fashion
  {
    id: '3',
    name: 'Designer Leather Handbag - Premium Collection',
    price: 149.99,
    originalPrice: 199.99,
    rating: 4.9,
    reviews: 924,
    image: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg',
    badge: 'Limited Edition',
    category: 'Fashion',
    description: 'Elevate your style with this exquisite handcrafted leather handbag from our premium designer collection.',
  },
  {
    id: '5',
    name: 'Luxury Silk Scarf - Hand Painted Design',
    price: 89.99,
    originalPrice: 129.99,
    rating: 4.8,
    reviews: 456,
    image: 'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg',
    badge: 'Artisan Made',
    category: 'Fashion',
    description: 'Add elegance to any outfit with this hand-painted silk scarf featuring unique artistic patterns.',
  },
  {
    id: 'f1',
    name: 'Premium Leather Jacket - Classic Style',
    price: 299.99,
    originalPrice: 399.99,
    rating: 4.7,
    reviews: 1876,
    image: 'https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg',
    badge: 'Trending',
    category: 'Fashion',
    description: 'Timeless leather jacket crafted from premium materials with a classic cut that never goes out of style.',
  },
  {
    id: 'f2',
    name: 'Designer Sunglasses - UV Protection',
    price: 179.99,
    originalPrice: 249.99,
    rating: 4.6,
    reviews: 743,
    image: 'https://images.pexels.com/photos/701877/pexels-photo-701877.jpeg',
    category: 'Fashion',
    description: 'Stylish designer sunglasses with 100% UV protection and polarized lenses for ultimate eye comfort.',
  },
  {
    id: 'f3',
    name: 'Cashmere Wool Sweater - Luxury Comfort',
    price: 189.99,
    originalPrice: 259.99,
    rating: 4.9,
    reviews: 567,
    image: 'https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg',
    badge: 'Luxury',
    category: 'Fashion',
    description: 'Ultra-soft cashmere wool sweater that combines luxury comfort with sophisticated style.',
  },
  {
    id: 'f4',
    name: 'Athletic Running Shoes - Performance',
    price: 129.99,
    originalPrice: 169.99,
    rating: 4.5,
    reviews: 2134,
    image: 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg',
    badge: 'Athletic',
    category: 'Fashion',
    description: 'High-performance running shoes with advanced cushioning and breathable materials for optimal comfort.',
  },

  // Home & Garden
  {
    id: '7',
    name: 'Premium Coffee Machine with Built-in Grinder',
    price: 449.99,
    originalPrice: 599.99,
    rating: 4.9,
    reviews: 743,
    image: 'https://images.pexels.com/photos/324028/pexels-photo-324028.jpeg',
    badge: 'Editor\'s Choice',
    category: 'Home & Garden',
    description: 'Brew café-quality coffee at home with our premium espresso machine featuring integrated ceramic grinder.',
  },
  {
    id: 'h1',
    name: 'Smart Air Purifier with HEPA Filter',
    price: 249.99,
    originalPrice: 329.99,
    rating: 4.7,
    reviews: 1456,
    image: 'https://images.pexels.com/photos/4239091/pexels-photo-4239091.jpeg',
    badge: 'Health',
    category: 'Home & Garden',
    description: 'Advanced air purifier with HEPA filtration system and smart controls for cleaner, healthier air.',
  },
  {
    id: 'h2',
    name: 'Luxury Bamboo Bed Sheets Set',
    price: 89.99,
    originalPrice: 129.99,
    rating: 4.8,
    reviews: 2341,
    image: 'https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg',
    category: 'Home & Garden',
    description: 'Ultra-soft bamboo bed sheets that are naturally hypoallergenic and temperature regulating.',
  },
  {
    id: 'h3',
    name: 'Modern LED Floor Lamp with Dimmer',
    price: 159.99,
    rating: 4.6,
    reviews: 892,
    image: 'https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg',
    badge: 'Modern',
    category: 'Home & Garden',
    description: 'Sleek modern floor lamp with adjustable brightness and color temperature for perfect ambiance.',
  },
  {
    id: 'h4',
    name: 'Organic Herb Garden Starter Kit',
    price: 49.99,
    originalPrice: 69.99,
    rating: 4.5,
    reviews: 1234,
    image: 'https://images.pexels.com/photos/1301856/pexels-photo-1301856.jpeg',
    badge: 'Organic',
    category: 'Home & Garden',
    description: 'Complete starter kit for growing fresh herbs at home with organic seeds and eco-friendly planters.',
  },

  // Sports
  {
    id: 's1',
    name: 'Professional Yoga Mat - Non-Slip',
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.8,
    reviews: 1876,
    image: 'https://images.pexels.com/photos/3822622/pexels-photo-3822622.jpeg',
    badge: 'Eco-Friendly',
    category: 'Sports',
    description: 'Premium yoga mat made from eco-friendly materials with superior grip and cushioning.',
  },
  {
    id: 's2',
    name: 'Adjustable Dumbbell Set - Home Gym',
    price: 299.99,
    originalPrice: 399.99,
    rating: 4.7,
    reviews: 743,
    image: 'https://images.pexels.com/photos/416717/pexels-photo-416717.jpeg',
    badge: 'Home Gym',
    category: 'Sports',
    description: 'Space-saving adjustable dumbbells that replace an entire weight set for home workouts.',
  },
  {
    id: 's3',
    name: 'Wireless Fitness Tracker - Heart Rate',
    price: 149.99,
    originalPrice: 199.99,
    rating: 4.6,
    reviews: 2134,
    image: 'https://images.pexels.com/photos/267394/pexels-photo-267394.jpeg',
    category: 'Sports',
    description: 'Advanced fitness tracker with heart rate monitoring, GPS, and comprehensive health insights.',
  },
  {
    id: 's4',
    name: 'Professional Tennis Racket - Carbon Fiber',
    price: 189.99,
    originalPrice: 249.99,
    rating: 4.9,
    reviews: 456,
    image: 'https://images.pexels.com/photos/209977/pexels-photo-209977.jpeg',
    badge: 'Pro',
    category: 'Sports',
    description: 'Professional-grade tennis racket made from lightweight carbon fiber for optimal performance.',
  },

  // Books
  {
    id: 'b1',
    name: 'The Art of Mindful Living - Hardcover',
    price: 24.99,
    originalPrice: 34.99,
    rating: 4.8,
    reviews: 1567,
    image: 'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg',
    badge: 'Bestseller',
    category: 'Books',
    description: 'Transform your life with practical mindfulness techniques and wisdom from leading experts.',
  },
  {
    id: 'b2',
    name: 'Complete Cookbook Collection - 3 Volume Set',
    price: 89.99,
    originalPrice: 129.99,
    rating: 4.9,
    reviews: 892,
    image: 'https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg',
    category: 'Books',
    description: 'Comprehensive cookbook collection featuring recipes from around the world with step-by-step instructions.',
  },
  {
    id: 'b3',
    name: 'Digital Photography Masterclass',
    price: 39.99,
    originalPrice: 59.99,
    rating: 4.7,
    reviews: 743,
    image: 'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg',
    badge: 'Educational',
    category: 'Books',
    description: 'Master the art of digital photography with professional techniques and creative inspiration.',
  },
  {
    id: 'b4',
    name: 'Modern Web Development Guide',
    price: 49.99,
    rating: 4.6,
    reviews: 1234,
    image: 'https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg',
    badge: 'Tech',
    category: 'Books',
    description: 'Comprehensive guide to modern web development covering the latest frameworks and best practices.',
  },

  // Health
  {
    id: 'he1',
    name: 'Organic Multivitamin Complex',
    price: 39.99,
    originalPrice: 54.99,
    rating: 4.7,
    reviews: 2341,
    image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg',
    badge: 'Organic',
    category: 'Health',
    description: 'Premium organic multivitamin complex with essential nutrients for optimal health and wellness.',
  },
  {
    id: 'he2',
    name: 'Essential Oil Diffuser Set',
    price: 79.99,
    originalPrice: 109.99,
    rating: 4.8,
    reviews: 1456,
    image: 'https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg',
    category: 'Health',
    description: 'Ultrasonic essential oil diffuser with premium oil collection for aromatherapy and relaxation.',
  },
  {
    id: 'he3',
    name: 'Digital Blood Pressure Monitor',
    price: 59.99,
    originalPrice: 79.99,
    rating: 4.6,
    reviews: 892,
    image: 'https://images.pexels.com/photos/4386467/pexels-photo-4386467.jpeg',
    badge: 'Medical',
    category: 'Health',
    description: 'Accurate digital blood pressure monitor with large display and memory storage for tracking.',
  },
  {
    id: 'he4',
    name: 'Protein Powder - Whey Isolate',
    price: 49.99,
    originalPrice: 69.99,
    rating: 4.5,
    reviews: 1876,
    image: 'https://images.pexels.com/photos/4397840/pexels-photo-4397840.jpeg',
    badge: 'Fitness',
    category: 'Health',
    description: 'High-quality whey protein isolate for muscle building and recovery with delicious flavors.',
  },

  // Automotive
  {
    id: 'a1',
    name: 'Wireless Car Charger Mount',
    price: 49.99,
    originalPrice: 69.99,
    rating: 4.6,
    reviews: 1234,
    image: 'https://images.pexels.com/photos/163016/crash-test-collision-60-km-h-distraction-163016.jpeg',
    badge: 'Wireless',
    category: 'Automotive',
    description: 'Convenient wireless charging mount for smartphones with secure grip and fast charging capability.',
  },
  {
    id: 'a2',
    name: 'Premium Car Dash Camera',
    price: 129.99,
    originalPrice: 179.99,
    rating: 4.7,
    reviews: 892,
    image: 'https://images.pexels.com/photos/163016/crash-test-collision-60-km-h-distraction-163016.jpeg',
    category: 'Automotive',
    description: 'High-definition dash camera with night vision and automatic incident recording for safety.',
  },
  {
    id: 'a3',
    name: 'All-Weather Floor Mats Set',
    price: 89.99,
    originalPrice: 119.99,
    rating: 4.8,
    reviews: 1567,
    image: 'https://images.pexels.com/photos/163016/crash-test-collision-60-km-h-distraction-163016.jpeg',
    badge: 'Protection',
    category: 'Automotive',
    description: 'Durable all-weather floor mats that protect your car interior from dirt, water, and wear.',
  },
  {
    id: 'a4',
    name: 'Bluetooth Car Audio Adapter',
    price: 29.99,
    originalPrice: 39.99,
    rating: 4.4,
    reviews: 2134,
    image: 'https://images.pexels.com/photos/163016/crash-test-collision-60-km-h-distraction-163016.jpeg',
    category: 'Automotive',
    description: 'Transform your car stereo with Bluetooth connectivity for wireless music streaming and calls.',
  },

  // Toys
  {
    id: 't1',
    name: 'Educational Building Blocks Set',
    price: 39.99,
    originalPrice: 54.99,
    rating: 4.9,
    reviews: 1876,
    image: 'https://images.pexels.com/photos/374103/pexels-photo-374103.jpeg',
    badge: 'Educational',
    category: 'Toys',
    description: 'Creative building blocks set that promotes STEM learning and develops problem-solving skills.',
  },
  {
    id: 't2',
    name: 'Remote Control Racing Drone',
    price: 149.99,
    originalPrice: 199.99,
    rating: 4.7,
    reviews: 743,
    image: 'https://images.pexels.com/photos/442587/pexels-photo-442587.jpeg',
    badge: 'Tech Toy',
    category: 'Toys',
    description: 'High-speed racing drone with HD camera and intuitive remote control for aerial adventures.',
  },
  {
    id: 't3',
    name: 'Interactive Learning Tablet for Kids',
    price: 79.99,
    originalPrice: 109.99,
    rating: 4.6,
    reviews: 1234,
    image: 'https://images.pexels.com/photos/374103/pexels-photo-374103.jpeg',
    category: 'Toys',
    description: 'Kid-friendly tablet with educational games, parental controls, and durable design.',
  },
  {
    id: 't4',
    name: 'Wooden Puzzle Game Collection',
    price: 24.99,
    originalPrice: 34.99,
    rating: 4.8,
    reviews: 892,
    image: 'https://images.pexels.com/photos/374103/pexels-photo-374103.jpeg',
    badge: 'Classic',
    category: 'Toys',
    description: 'Beautiful wooden puzzle collection that challenges minds and develops cognitive skills.',
  },
];

export const sampleProducts = allProducts.slice(0, 12);
export const featuredProducts = allProducts.filter(p => p.badge === 'Best Seller' || p.badge === 'New' || p.badge === 'Limited Edition').slice(0, 4);
export const bestSellers = allProducts.filter(p => p.badge === 'Best Seller' || p.reviews > 1500);

export const getProductsByCategory = (category: string): Product[] => {
  return allProducts.filter(product => product.category === category);
};

export const categories = [
  'Electronics', 'Fashion', 'Home & Garden', 'Sports', 'Books', 'Health', 'Automotive', 'Toys'
];